### ISSUE TITLE
feat: add "Breakdown average" column in RubricQuestionStatisticsComponent

### ISSUE THREAD

**Issue by adamezzaim** [tjex/teammates#5]
Modify function getQuestionCsvStats(question: QuestionOutput) in src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts to add the desired column

**Comment by tjex** [comment]
closed with [c0abda2](https://github.com/tjex/teammates/commit/c0abda2710894842ef0f5a381c94f6a004cc3109)
